apiVersion: v1
kind: Template
metadata:
  name: f8notification-config
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: f8notification
  type: Opaque
  data:
    madrill.api: eHh4eHh4
    service.account.id: 4c83ca2d-6dcc-41c9-ac7d-b068ad4d17c5
    service.account.secret: $2a$04$sbC/AfW2c33hv8orGA.1D.LXa/.IY76VWhsfqxCVhrhFkDfL0/XGK
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f8notification
  type: Opaque
  data:
    wit.api: https://api.prod-preview.openshift.io
    keycloak.url: https://sso.prod-preview.openshift.io
    keycloak.realm: fabric8-test